//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sirket.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SirketZT : DbContext
    {
        public SirketZT()
            : base("name=SirketZT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<cihaz> cihaz { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<marka_kategori> marka_kategori { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tel_marka> tel_marka { get; set; }
        public virtual DbSet<zimmet> zimmet { get; set; }
    }
}
