//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sirket.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class zimmet
    {
        public int cihaz_id { get; set; }
        public int kullanici_id { get; set; }
        [DisplayName("Zimmet Tarih")]
        public System.DateTime zimmet_tarih { get; set; }
        public int zimmet_id { get; set; }
        public Nullable<int> telmarka_id { get; set; }
    
        public virtual cihaz cihaz { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual tel_marka tel_marka { get; set; }
    }
}
